### ISSUE TITLE
Can't sign into therapist account after patient accepts request

### ISSUE THREAD

**Issue by dajinchu** [ReGame-VR/WHAM-api#4] opened 2018-11-03 19:59 UTC
Steps to reproduce:

1. Create a therapist account
2. Request a patient
3. Login to the patient account
4. Accept the therapist request

After that, logging into the therapist account gets past the login screen, but displays Page Not Found.

**Comment by ryan-bradford** [comment] 2018-11-03 23:33
Hmmm, so I just wrote a test case. What happens now is:

1. therapist1 creates their account, the patient creates their account.
2. They both log in .
3. therapist1 request the patient
4. the patient accepts the request
5. therapist one CAN log in. 

So I was not able to reproduce the bug...

Although, it could be something having to do with the web side of things (which I haven't tried).

**Comment by dajinchu** [comment] 2018-11-04 00:34
So I think the therapist can authenticate, but then when they go to the `therapists/:id` url, they get a Page Not Found, which I think may have something to do with the authorization?

**Comment by ryan-bradford** [comment] 2018-11-05 18:15
OK, I figured out what the bug is - I think. It's not that the therapist can't log in or that they aren't authorized; it's because of the mildly confusing login process.

When you log in as a therapist, it directs you to from /login/therapist to /therapists/ID
Then when you log in as a patient, it directs you from /login/patient to /patients/ID
Then you accept the request.
Then you press back in the browser (bringing you to /login/patient) and you type in the therapist login details.
It succeeds in authentication, but then it directs you to /patients/therapistID (because you were at the patient login page). It then recognized that there is not PATIENT with ID of therapistID, so it directs you to Page Not Found.

I'm gonna add some way for the login process to be type specific.

Then if the bug still occurs, we have a greater problem...

EDIT: Just pushed the fix, see if your problem still happens.

**Comment by dajinchu** [comment] 2018-11-05 19:08
Nice. Looks like it's fixed.

**Closed as completed** 2018-11-05 19:08 UTC
Labels: bug
